### ISSUE TITLE
botocore error on script completion

### ISSUE THREAD

**Issue by Scotchman0** [Scotchman0/CellProfiler_Ubuntu_Installer#3]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docutils 0.16 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('docutils<0.16,>=0.10'), {'botocore'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cellprofiler", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3252, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3236, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3265, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docutils 0.16 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('docutils<0.16,>=0.10'), {'botocore'})

— re-running install bundle and log-out enabled to capture error line with init. 

Confirmed error reproduced on known good system baseline
 botocore (older) has a problem with docutils (newer)

**Comment by Scotchman0** [comment]
Resolved: update botocore to latest version baseline with sudo python -m pip uninstall botocore -y
&& sudo python -m pip install botocore -y

todo: add latest botocore pull manually instead of allowing cellprofiler default baseline to call older variation. (functional workaround implemented)

merged with master - 1/20/20
